# Generated by Django 3.1.1 on 2020-12-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('response_type', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=100)),
                ('sentiment', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='UserReplies',
        ),
    ]
