# Generated by Django 3.1.1 on 2021-01-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megan', '0002_auto_20201230_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='response_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='replies',
            name='sentiment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='replies',
            name='text',
            field=models.TextField(),
        ),
    ]
