# Generated by Django 3.1.5 on 2021-02-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megan', '0003_auto_20210104_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('messages', models.JSONField()),
            ],
        ),
    ]
