# Generated by Django 3.1.5 on 2021-02-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Megan', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserMessages',
        ),
    ]
