# Generated by Django 3.1.5 on 2021-02-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Megan', '0006_remove_usermessages_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessages',
            old_name='user_id',
            new_name='_id',
        ),
    ]
