# Generated by Django 3.1.5 on 2021-02-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Megan', '0008_auto_20210226_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessages',
            old_name='text',
            new_name='name',
        ),
    ]
