# Generated by Django 3.1.5 on 2021-02-27 11:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megan', '0009_auto_20210226_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user_id', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='UserMessages',
        ),
    ]
