# Generated by Django 3.1.5 on 2021-02-27 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megan', '0010_auto_20210227_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.TextField(default='username', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.TextField(default='user', max_length=50),
        ),
    ]
