# Generated by Django 3.1.5 on 2021-02-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megan', '0011_auto_20210227_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
